version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audit_trail
    ports:
      - '1234:5432'
    volumes:
      - audit-trail-nestjs:/var/lib/postgresql/data

volumes:
  audit-trail-nestjs:
